package info.curtbinder.arduino.tool;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

abstract class RABaseFile {
    public static final String FILE_HEADER = "" +
            "/*\n" +
            " * Copyright 2020 Reef Angel\n" +
            " *\n" +
            " * Licensed under the Apache License, Version 2.0 (the \"License\");\n" +
            " * you may not use this file except in compliance with the License.\n" +
            " * You may obtain a copy of the License at\n" +
            " *\n" +
            " * http://www.apache.org/licenses/LICENSE-2.0\n" +
            " *\n" +
            " * Unless required by applicable law or agreed to in writing, software\n" +
            " * distributed under the License is distributed on an \"AS IS\" BASIS,\n" +
            " * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n" +
            " * See the License for the specific language governing permissions and\n" +
            " * limitations under the License.\n" +
            " */\n" +
            "\n";

    protected String getAutoGeneratedString(String filename) {
        DateTimeFormatter df = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");
        return "// AutoGenerated file by Arduino (Reef Angel)\n" +
                "// Generated on " + df.format(LocalDateTime.now()) + " for INO file: " + filename + "\n";
    }

    abstract public void init(String sketchFolder, String sketchFileName);
    abstract public void loadDefaults();
    abstract public boolean hasPrerequisites();
    abstract public void process(String code);
    abstract public String generateFile();
    abstract public String getFileName();
}